name = "cs2-case-opener"
main = "src/worker.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "f477af41237d6715566cd34400604c7f"

[[d1_databases]]
binding = "DB"
database_name = "cs2-case-opener"
database_id = "3bafcec3-1d62-456d-9b14-5c5698ae0da0"
migrations_dir = "src/db/migrations"

[durable_objects]
bindings = [
  { name = "RT", class_name = "Realtime" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Realtime"]

[assets]
directory = "../web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[triggers]
crons = ["*/5 * * * *"]
